name: Test

on:
  - push
  - pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install
      - name: Run test
        run: npm run test
